title:              Oskarin Projektit
email:              oskari.vihonen@gmail.com
description:        Oskarin projektisivut!
author:             Oskari Vihonen
baseurl:            ""
url:                ""

# Social Profiles
twitter_username:
github_username:    oskarivihonen
facebook_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

sass:
  sass_dir: _sass
  style: compressed
  
# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site